Description = "Welcome to Shadiao Garden. Elements including mathematics, programming, games, ridicule, 'chonglang', science, and memes."
Keywords =  "Blog, Math, Programming, Meme, Science, Funny, Technology, Share"
Subtitle = "Shadiao makes people forward!"
AuthorImg = "/img/avatar.png"
AuthorName = "Idiot-Idolt"
Introduce = "Idiot is idolt!"
DateFormat = "2006/01/02"
YearFormat = "2006Y"
MonthFormat = "01/02"

ArticleDeclContent = "This blog post article is under the <a href='https://creativecommons.org/licenses/by-nc-sa/3.0/' target='_blank' style='text-decoration: underline;'>CC BY-NC-SA 3.0</a> license,Please indicate the source!"

[Footer]
  StorageLink = "https://github.com/jcq15/jcq15.github.io"
  StorageName = "Github Repository"
  #ICPLink = "http://beian.miit.gov.cn"
  #ICPNo = "ICP.NO 18047355"

[[Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/jcq15/"


#[[Links]]
#  Name = "LiaoXueFeng"
#  Permalink = "https://www.liaoxuefeng.com/"