[TagsCloud]
  Enable = true
  Limit = 10

[Share]
  Enable = true
  AddthisId = "Your AddthisId"

[Comment]
  Enable = true
  Module = "Utterances"
  LiveReId = "Your LiveReId"
  WalineSerURL = "Your WalineSerURL"

  # If Module is "Utterances",see https://utteranc.es/
  #UtterancesRepo = "owner/repo"
  UtterancesTheme = "github-light"
  UtterancesTitle = "title"

  # utterance 评论 see: https://utteranc.es/
  UtterancesRepo = "jcq15/blog"
  #UtterancesIssueTerm = "title"

[LeanCloud]
  AppId = "Your LCAppId"
  AppKey = "Your LCAppKey"
  ServerURL = "Your LCServer"

[Statis]
  BusuanziCounter = true
#  CNNZSiteId = "Your CNNZSiteId"
#  BaiduSiteId = "Your BaiduSiteId"
#  GoogleSiteId = "Your GoogleSiteId"

[OnlineIM]
  Enable = false
#  DaoVoiceId = "Your DaoVoiceId"

[Others]
#  RevolverMapId = "Your RevolverMapId"